# Generated by Django 4.2.3 on 2023-07-29 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('main_image', models.URLField(blank=True, null=True)),
                ('extra_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
