# Generated by Django 4.2.3 on 2023-07-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_text',
            field=models.TextField(default='text...'),
        ),
    ]
