# Generated by Django 4.2.3 on 2023-08-05 13:48

import django.core.validators
from django.db import migrations, models
import tattoo_web.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_main_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='extra_image',
            field=models.ImageField(upload_to='images', validators=[tattoo_web.core.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(upload_to='images', validators=[tattoo_web.core.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
