# Generated by Django 4.2.3 on 2023-08-08 10:18

from django.db import migrations, models
import tattoo_web.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_sub_title_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Byline',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='Conclusion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_image',
            field=models.ImageField(default=None, upload_to='images', validators=[tattoo_web.core.utils.validate_file_size]),
            preserve_default=False,
        ),
    ]
