# Generated by Django 4.2.3 on 2023-08-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_byline_article_conclusion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Byline',
            new_name='byline',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Conclusion',
            new_name='conclusion',
        ),
    ]
