# Generated by Django 4.2.3 on 2023-08-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_userphotocomment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistphotocomment',
            options={'ordering': ['-date_time_of_publication']},
        ),
        migrations.AlterModelOptions(
            name='userphotocomment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
