# Generated by Django 4.2.3 on 2023-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
    ]
