# Generated by Django 4.2.3 on 2023-08-07 15:50

from django.db import migrations, models
import tattoo_web.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='images', validators=[tattoo_web.core.utils.validate_file_size]),
            preserve_default=False,
        ),
    ]
