# Generated by Django 4.2.3 on 2023-07-31 14:19

import django.core.validators
from django.db import migrations, models
import tattoo_web.core.model_mixins
import tattoo_web.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, validators=[tattoo_web.photos.validators.validate_file_size])),
                ('description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_of_publication', models.DateField(auto_now=True)),
            ],
            bases=(tattoo_web.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
