# Generated by Django 4.2.3 on 2023-07-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='ArtistPhoto',
        ),
    ]
