# Generated by Django 4.2.3 on 2023-08-05 15:53

import django.core.validators
from django.db import migrations, models
import tattoo_web.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_artistphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistphoto',
            name='description',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='description',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images', validators=[tattoo_web.core.utils.validate_file_size]),
        ),
    ]
