# Generated by Django 4.2.3 on 2023-08-10 09:49

from django.db import migrations, models
import tattoo_web.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_artistphoto_options_alter_userphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[tattoo_web.core.utils.validate_file_size]),
        ),
    ]
